// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calculator.proto
#ifndef GRPC_calculator_2eproto__INCLUDED
#define GRPC_calculator_2eproto__INCLUDED

#include "calculator.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// The calculator service definition
class Calculator final {
 public:
  static constexpr char const* service_full_name() {
    return "Calculator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Adds 1 to a number
    virtual ::grpc::Status AddOne(::grpc::ClientContext* context, const ::Number& request, ::Number* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Number>> AsyncAddOne(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Number>>(AsyncAddOneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Number>> PrepareAsyncAddOne(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Number>>(PrepareAsyncAddOneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Adds 1 to a number
      virtual void AddOne(::grpc::ClientContext* context, const ::Number* request, ::Number* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddOne(::grpc::ClientContext* context, const ::Number* request, ::Number* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Number>* AsyncAddOneRaw(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Number>* PrepareAsyncAddOneRaw(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddOne(::grpc::ClientContext* context, const ::Number& request, ::Number* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Number>> AsyncAddOne(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Number>>(AsyncAddOneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Number>> PrepareAsyncAddOne(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Number>>(PrepareAsyncAddOneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddOne(::grpc::ClientContext* context, const ::Number* request, ::Number* response, std::function<void(::grpc::Status)>) override;
      void AddOne(::grpc::ClientContext* context, const ::Number* request, ::Number* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Number>* AsyncAddOneRaw(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Number>* PrepareAsyncAddOneRaw(::grpc::ClientContext* context, const ::Number& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddOne_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Adds 1 to a number
    virtual ::grpc::Status AddOne(::grpc::ServerContext* context, const ::Number* request, ::Number* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddOne() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddOne(::grpc::ServerContext* context, ::Number* request, ::grpc::ServerAsyncResponseWriter< ::Number>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddOne<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddOne() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Number, ::Number>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Number* request, ::Number* response) { return this->AddOne(context, request, response); }));}
    void SetMessageAllocatorFor_AddOne(
        ::grpc::MessageAllocator< ::Number, ::Number>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Number, ::Number>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddOne(
      ::grpc::CallbackServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddOne<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddOne() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddOne() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddOne(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddOne() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddOne(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddOne(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddOne() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Number, ::Number>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Number, ::Number>* streamer) {
                       return this->StreamedAddOne(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddOne(::grpc::ServerContext* /*context*/, const ::Number* /*request*/, ::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddOne(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Number,::Number>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddOne<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddOne<Service > StreamedService;
};


#endif  // GRPC_calculator_2eproto__INCLUDED
